name: Atualizador Diario dos Bancos de Precos

on:
  schedule:
    - cron: '0 3 * * *' 
  workflow_dispatch:

jobs:
  atualizar-banco:
    runs-on: ubuntu-latest

    steps:
      - name: Clonando o repositorio
        uses: actions/checkout@v3

      - name: Configurando o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalando as Ferramentas
        run: |
          pip install requests pandas urllib3 streamlit

      - name: Rodando o Robo Invisivel CE
        run: python robo_invisivel.py

      - name: Rodando o Trator Nacional
        run: python robo_nacional.py

      - name: Salvando os Bancos Atualizados
        run: |
          git config --global user.name "Robo Atualizador"
          git config --global user.email "robo@comprasgov.com"
          git add banco_compras.db banco_nacional.db
          git commit -m "Atualizacao diaria automatica" || exit 0
          git push
